version: '3'
services:
  psql:
    image: postgres:9.6
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  backend:
    image: lemmih/clozecards_backend
    links:
      - psql
    volumes:
      - /root/credentials:/root/.aws/credentials
  frontend:
    image: lemmih/clozecards_frontend
    ports:
      - "80:80"
      - "443:443"
    links:
      - backend:backend
    volumes:
      - "./webroot:/webroot/"
      - "/etc/letsencrypt/:/ssl/"
volumes:
  dbdata:  
